seed: 13
batch_size: 1024
epochs: 10

paths:
  scvi_model_dir: artifacts_v2/scvi_k562_max200k_control_only/scvi_K562/
  factor_U: artifacts_v2/learned_factor_encoders/factor_W_K562.npy
  index_parquet: artifacts_v2/scvi_k562_max200k_control_only/scvi_z_K562.npz #parquet
  datasets:
    - id: DixitRegev
      z_parquet: artifacts_v2/DixitRegev/z_K562.parquet
      h5ad: /data/scperturb/DixitRegev2016.h5ad
      knn_parquet: artifacts_v2/DixitRegev/knn_controls.parquet
    - id: ReplogleWeissmanGWPS
      z_parquet: artifacts_v2/ReplogleWeissmanGWPS/z_K562.parquet
      h5ad: /data/scperturb/ReplogleWeissman2022_K562_gwps.h5ad
      knn_parquet: artifacts_v2/ReplogleWeissmanGWPS/knn_controls.parquet

data:
  n_genes: 6281
  L_ref: 1.0e4
  transform_batch: null
  gene_names: []

model:
  z_dim: 32
  propagator:
    hidden: 256
    layers: 2
    steps: 2
    dropout: 0.0
    use_env_film: true
    use_target_cond: true
    target_embed_dim: 32
  step0:
    hidden: 64
    init_eff: 0.9
    mode: down
  mediated:
    F: 273
    hidden: 256
    use_factor_feats: false
    a_dim: 0
    nonneg: true
    dropout: 0.0
  direct:
    hidden: 256
    dropout: 0.0

optim:
  name: adamw
  lr: 2.0e-4
  weight_decay: 1.0e-4

loss:
  distribution:
    type: swd     # swd | mmd | energy
    weight: 1.0
  rex:
    weight: 0.1
  irm:
    weight: 0.0
    use_target_only: true
  consistency:
    weight: 0.5
  direct:
    l1: 1.0e-4
    orth_to_U: 0.0
